import {VisualizacaoModel} from "~/models/visualizacao.model";

export const hospital: Array<VisualizacaoModel> = [
    {
        id: 1,
        nome: 'Hospital Regional de Paraíso ',
        localizacao: {latitude: -10.1808948, longitude: -48.9131606},
        endereco: 'RUA 03 QD 02 LT 01 A 19 ',
        bairro: 'Setor Aeroporto',
        telefone: '(63) 3904-1200',
        descricao: '',
        imagem: '~/imagens/campanha2.jpg',
        servicos: [],
        cidade: 'Paraiso do Tocantins',
        estado: 'TO',
        created_at: 'string'
    },
    {
        id: 2,
        nome: 'Hospital Modelo',
        localizacao: {latitude: -10.1752863, longitude: -48.8831248},
        endereco: 'Rua Tapajós, Quadra 24, Lote1, 260 ',
        bairro: 'Centro',
        telefone: '(63) 3602-1188',
        descricao: '',
        cidade: 'Paraiso do Tocantins',
        estado: 'TO',
        imagem: '~/imagens/campanha2.jpg',
        servicos: [],
        created_at: 'string'
    },
    {
        id: 3,
        nome: 'Centro Médico Paraíso',
        localizacao: {latitude: -10.1749416, longitude: -48.8848086},
        endereco: 'Rua Mal Rondon Q 25, 104 lt 7 ',
        bairro: 'Centro',
        telefone: '(63) 3602-1399',
        descricao: '',
        cidade: 'Paraiso do Tocantins',
        estado: 'TO',
        imagem: '~/imagens/campanha2.jpg',
        servicos: [],
        created_at: 'string'
    },


]
export const ubs: Array<VisualizacaoModel> = [
    {
        id: 4,
        nome: 'UBS Norte Paraíso ',
        localizacao: {latitude: -10.174507, longitude: -48.900191},
        endereco: 'Rua Dom Pedro Ii Qd 151 Lt10',
        bairro: 'Jardim Paulista ',
        telefone: '(63) 3904-1442',
        descricao: '',
        cidade: 'Paraiso do Tocantins',
        estado: 'TO',
        imagem: '~/imagens/campanha2.jpg',
        servicos: [
            { s: 'ESTRATEGIA DE SAUDE DA FAMILIA', c: 'SAUDE BUCAL MI' },
            { s: 'ESTRATEGIA DE SAUDE DA FAMILIA', c: 'SAUDE DA FAMILIA' },
            { s: 'SERVICO DE ATENCAO A SAUDE DO TRABALHADOR', c: 'ATENDIMENTO ACOMPANHAMENTO EM SAUDE DO TRABALHADOR' },
            { s: 'SERVICO DE ATENCAO AO PACIENTE COM TUBERCULOSE', c: 'DIAGNOSTICO E TRATAMENTO' },
        ],
        created_at: 'string'
    },
    {
        id: 5,
        nome: 'UBS Sul Paraíso',
        localizacao: {latitude: -10.194348, longitude: -48.889405},
        endereco: 'Av 23 De Outubro',
        bairro: 'Pouso Alegre',
        telefone: '(63) 3904-1443',
        descricao: '',
        servicos: [],
        cidade: 'Paraiso do Tocantins',
        estado: 'TO',
        imagem: '~/imagens/campanha2.jpg',
        created_at: 'string'
    },
    {
        id: 6,
        nome: 'UBS Clovis Carneiro Campos',
        localizacao: {latitude: 0, longitude: 0},
        endereco: 'Av Brasil, Nª985',
        bairro: 'Vila Regina',
        telefone: '  -',
        descricao: '',
        servicos: [
            { s: 'ESTRATEGIA DE SAUDE DA FAMILIA', c: 'SAUDE BUCAL MI' },
            { s: 'SERVICO DE ATENCAO A SAUDE DO TRABALHADOR', c: 'ATENDIMENTO ACOMPANHAMENTO EM SAUDE DO TRABALHADOR' },
            { s: 'SERVICO DE ATENCAO AO PACIENTE COM TUBERCULOSE', c: 'DIAGNOSTICO E TRATAMENTO' },
        ],
        cidade: 'Paraiso do Tocantins',
        estado: 'TO',
        imagem: '~/imagens/ubs/ubs-clovis-carneiro.jpg',
        created_at: 'string'
    },
    {
        id: 7,
        nome: 'UBS Vila Milena Paraíso',
        localizacao: {latitude: -10.160145, longitude: -48.887119},
        endereco: 'Av Santos Dumont',
        bairro: 'Vila Milena',
        telefone: '(63) 3904-1579',
        descricao: '',
        servicos: [],
        cidade: 'Paraiso do Tocantins',
        estado: 'TO',
        imagem: '~/imagens/campanha2.jpg',
        created_at: 'string'
    },
    {
        id: 8,
        nome: 'UBS Sespe Paraíso',
        localizacao: {latitude: -10.180484, longitude: -48.887435},
        endereco: 'Rua Santos Dumont',
        bairro: 'Centro',
        telefone: '(63) 3602-3775',
        descricao: '',
        servicos: [],
        cidade: 'Paraiso do Tocantins',
        estado: 'TO',
        imagem: '~/imagens/campanha2.jpg',
        created_at: 'string'
    },
    {
        id: 9,
        nome: 'UBS Oeste Paraiso',
        localizacao: {latitude: 2, longitude: 4},
        endereco: 'Rua Bernadino Maciel',
        bairro: 'Setor Aeroporto',
        telefone: '(63) 3904-1445',
        descricao: '',
        servicos: [],
        cidade: 'Paraiso do Tocantins',
        estado: 'TO',
        imagem: '~/imagens/campanha2.jpg',
        created_at: 'string'
    },
    {
        id: 10,
        nome: 'UBS Gentil Costa',
        localizacao: {latitude: 0, longitude: 0},
        endereco: 'Rua L 14 Esquina com L 24',
        bairro: 'Interlagos',
        telefone: '   -',
        descricao: '',
        servicos: [],
        cidade: 'Paraiso do Tocantins',
        estado: 'TO',
        imagem: '~/imagens/ubs/ubs-gentil-costa.jpg',
        created_at: 'string'
    },
]
